spring:
  application:
    name: "patient-manaager"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/servicio_turnos?serverTimezone=UTC
    username: root
    password: Popi_07102022
server:
  port: 9002